### ISSUE TITLE
Feature request: accept image for graph

### ISSUE THREAD

**Issue by lwh** [avinassh/rockstar#2]
Thanks for the amazing tool! Would it be possible to make it accept an image or URL as input and then convert/draw it in the graph?

**Comment by avinassh** [comment]
Hey! There is already one library which does exactly what you are asking for, however I am not able to recall it's name at the moment. I will update here once I remember it. 

Also, I am not sure Rockstar should do it. Rockstar fills all the boxes (i.e. each commit for everyday), so that you get longest streak :stuck_out_tongue: But this is interesting anyways and I will look into it. Thanks for the feedback!

**Comment by SanketDG** [comment]
@avinassh [This](https://github.com/IonicaBizau/github-contributions) is pretty close to what @lwh wants.

**Comment by avinassh** [comment]
[This](https://github.com/gelstudios/gitfiti) one too.

**Comment by pikesley** [comment]
Nice

My very own [Github Vandalism webservice](http://pokrovsky.herokuapp.com/)

And me [speaking about it](https://www.youtube.com/watch?v=Qt_J0jNqtZg)

:smile:

**Comment by avinassh** [comment]
Closing this issue. I find this feature not really relevant
